# Check https://circleci.com/docs/2.0/language-java/ for more details
#
# Wanting to do push to github on release, look at https://circleci.com/blog/publishing-to-github-releases-via-circleci/
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      #MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: cd edu.harvard.i2b2.server-common && ant clean dist war

      - store_artifacts:
          path: edu.harvard.i2b2.server-common/dist/i2b2.war.zip
          destination: i2b2-war
